### ISSUE TITLE
fails when --environment=production

### ISSUE THREAD

**Issue by dbinetti** [simplabs/ember-cli-simple-auth#12]
I've been able to get things to work (custom server, example #6) in ember server within a development environment.  But when I try to run `ember serve --environment=production` I get a blank page.  The console reports `Uncaught Error: Could not find module simple-auth/authenticators/base`.  

I'm a total noob, so perhaps I'm doing something else wrong?  I've searched for hours to no avail...

Thanks!

**Comment by soundarapandian** [comment]
@dbinetti How did you resolved this issue?. I am facing exact issue even in development mode.
