### ISSUE TITLE
Could not find addon with name: ember-cli-simple-auth

### ISSUE THREAD

**Issue by rvan1** [simplabs/ember-cli-simple-auth#27]
I was not able to get the simple-auth mixins to work (import) in my upgraded EAK-based app, so have migrated it to Ember CLI (0.2.3). They still don't work...

Error: Could not find module 'simple-auth/mixins/application-route-mixin' imported from 'cro/routes/application

So now I tried to install the 'simple-auth addon' with 'ember install ember-cli-simple-auth', but then I get...

  Installed packages for tooling via npm.
  Install failed. Could not find addon with name: ember-cli-simple-auth

**Comment by rvan1** [comment]
Seems to work now. I added a '~' to the bower.json entry ("ember-simple-auth": "0.8.0-beta.1"), then ran 'bower update', then tried the addon install again. The '~' got removed, but the install worked...

Installing browser packages via BowerInstalling browser packages via Bower.Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.1
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

While I didn't try to run 'ember generate' and the guide indicates it should be done for older versions of CLI, but I went ahead and ran it anyway after the install message seemed to suggest I should...

$ ember generate ember-cli-simple-auth
version: 0.2.3
installing
Installing browser packages via BowerInstalling browser packages via Bower.Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.1
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.1
Installed browser packages via Bower.

Well, now my app comes up with the mixin imported into the 'application' route so I think I'm good to go in working out how to use simple-auth. Thx

**Comment by dylanfoster** [comment]
This still seems like an issue to me. Users should be able to install ember-cli packages using the conventional methods (i.e. ember install ember-cli-simple-auth) without having to use workarounds.

**Comment by marcoow** [comment]
@dylanfoster: what specifically doesn't work for you?

**Comment by dylanfoster** [comment]
The only thing that doesn't work for me is ember install ember-cli-simple-auth. We can use a workaround by doing npm install --save-dev ember-cli-simple-auth then ember g ember-cli-simple-auth, but, we shouldn't need to use workarounds to install addons.

I know there's been some active development around ember install, specifically with regards to blueprints and their entity names, which could be the cause of this issue, but this is the fist time I've run into this so far.

**Comment by marcoow** [comment]
@dylanfoster: can you be more specific (error messages, etc.)?

**Comment by avinmathew** [comment]
I encountered the same issue on Ember CLI 0.2.7 when running `ember install ember-cli-simple-auth`. My workaround was running `ember install:addon ember-cli-simple-auth`. This prints the deprecation message, but at least everything installs correctly.
