### ISSUE TITLE
Can't install ember cli simple auth 

### ISSUE THREAD

**Issue by deeksy** [simplabs/ember-cli-simple-auth#28]
Having problems install ember cli simple auth with the following output.  This has happened repeatedly in different setups:

~/git-dashboard/client 🍔  ember --version
version: 0.2.3
node: 0.12.2
npm: 2.7.6
~/git-dashboard/client 🍔  ember install ember-cli-simple-auth
version: 0.2.3
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.2
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

The same thing happens for other ember-cli-simple-auth addons (oauth2, torii, etc.)

**Comment by marcoow** [comment]
That's a bug in Ember CLI, the addon actually installs correctly though, see #26.
