### ISSUE TITLE
Ember generate error message when installing

### ISSUE THREAD

**Issue by rtm** [simplabs/ember-cli-simple-auth#30]
$ ember install ember-cli-simple-auth
    version: 0.2.3
    Installed packages for tooling via npm.
    installing
    Installing browser packages via Bower...
      cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.2
    Installed browser packages via Bower.
    installing
    The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

Any idea what this error might be? As far as I can tell, the installation did not proceed successfully. for instance, I see no ember-simple-auth initializer.

**Comment by marcoow** [comment]
see e.g. #28
