### ISSUE TITLE
[Feature request] Upgrade to full cli version

### ISSUE THREAD

**Issue by QuantumInformation** [simplabs/ember-cli-simple-auth#35]
Would it be possible to upgrade to a full cli version? This would also have the advantage of having a dummy app  where you could run the examples as in the simple-auth examples.

**Comment by marcoow** [comment]
see simplabs/ember-simple-auth#522

**Comment by QuantumInformation** [comment]
Ah nice:)

**Comment by QuantumInformation** [comment]
Closing as is in pipeline from original lib.

**Comment by QuantumInformation** [comment]
@marcoow so currently we have to include the script like this before we can use the mixins and authenticators in a cli-app?

    <script src="bower_components/ember-simple-auth/simple-auth.js"></script>

**Comment by marcoow** [comment]
No, you install this Ember CLI Addon as [described here](https://github.com/simplabs/ember-cli-simple-auth#installation).

**Comment by QuantumInformation** [comment]
thanks, thats what I done before, but didn't realise it was merged in to vendor.
