### ISSUE TITLE
(Possible) Suggestion: Use Instance Initializer

### ISSUE THREAD

**Issue by green-arrow** [simplabs/ember-cli-simple-auth#37]
Backgorund:

I have a custom OAuth authenticator. As part of the `restore` method, I'm calling into an `Ember.service` to do some setup based on the current user. That service requires the use of the `ember-data` `store` service. As of beta 19, `ember-data` uses instance initializer, which means the `store` does not exist at the time the `restore` method of the authenticator is called.

Is updating to an instance initializer here the way to go?

**Comment by marcoow** [comment]
The introduction of instance initializers is tracked here: simplabs/ember-simple-auth#517
