### ISSUE TITLE
Not compatible with Ember 2.0

### ISSUE THREAD

**Issue by DanielOchoa** [simplabs/ember-cli-simple-auth#39]
Ember 2.0 changes the way things get registered on the container from initializers (It got deprecated since 1.13 I think) so now ember-cli-simple-auth does not work for 2.0.

**Comment by marcoow** [comment]
see simplabs/ember-simple-auth#602 et al

**Comment by DanielOchoa** [comment]
Thanks. Next time I'll check other closed issued and PR queue first.
